### ISSUE TITLE
发现图片有时无法加载，黑屏

### ISSUE THREAD

**Issue by cybkw** [jenly1314/ImageViewer#3]

**Comment by jenly1314** [comment]
请贴出相关日志，并确认已经配置了加载器（imageLoader必须配置，目前内置的有GlideImageLoader或PicassoImageLoader，也可以自己实现）

**Comment by houkhan** [comment]
我也出现了此问题
我的依赖版本：com.github.jenly1314:imageviewer:1.0.4
我的使用方式：
ImageViewer.load(imgs)//要加载的图片数据，单张或多张
                    .imageLoader(new GlideImageLoader())//加载器，imageLoader必须配置，目前内置的有GlideImageLoader或PicassoImageLoader，也可以自己实现
                    .selection(index)
                    .indicator(true)
                    .start(mActivity);
                    
                    经过断点跟随 发现是  ImageViewerAdapter 的 displayImage 的时候 
                    ViewerSpec.INSTANCE.imageLoader 为空了没有加载图片
