### ISSUE TITLE
加载图片黑屏 未 成功加载

### ISSUE THREAD

**Issue by houkhan** [jenly1314/ImageViewer#8]
我也出现了此问题
我的依赖版本：com.github.jenly1314:imageviewer:1.0.4
我的使用方式：
ImageViewer.load(imgs)//要加载的图片数据，单张或多张
.imageLoader(new GlideImageLoader())//加载器，imageLoader必须配置，目前内置的有GlideImageLoader或PicassoImageLoader，也可以自己实现
.selection(index)
.indicator(true)
.start(mActivity);
经过断点跟随 发现是  ImageViewerAdapter 的 displayImage 的时候 
ViewerSpec.INSTANCE.imageLoader 为空了没有加载图片

**Comment by houkhan** [comment]
补充 加载之前触发了 
ImageViewerActivity 的  onDestroy 方法 中的 mViewerSpec.imageLoader = null; 清空了

**Comment by jenly1314** [comment]
> 补充 加载之前触发了 ImageViewerActivity 的 onDestroy 方法 中的 mViewerSpec.imageLoader = null; 清空了

什么原因会在加载之前触发`onDestroy`，是打开了多个ImageViewerActivity吗?

**Comment by houkhan** [comment]
不是 暂时没找到原因

**Comment by jenly1314** [comment]
抽空测了下，没复现你描述的问题；猜测可能是延迟触发的`onDestroy`导致；不过不重要了，发了新版本，排除了这种可能性。
